TITLE = 'Nutty Dash'
WIDTH = 960
HEIGHT = 544
FPS = 60
TILESIZE = 16
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE
#Настройки игрока
PLAYER_ACC = 0.9
PLAYER_FRICTION = -0.15
PLAYER_GRAV = 0.5

